[platformio]
default_envs = esp32_babyboi
src_dir = ./src
data_dir = ./data
include_dir = ./include
build_cache_dir = ./.pio/.buildcache
packages_dir = ./.pio/packages
cache_dir = ./.pio/cache
extra_configs = platformio_user.ini

;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
; Baseline build environment                                         ;
; https://docs.platformio.org/en/latest/projectconf/section_env.html ;
;~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~;
[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_compat_mode = strict
lib_deps =
    adafruit/Adafruit PWM Servo Driver Library
    bblanchon/ArduinoJson
    djgrrr/Int64String
    forkineye/ESPAsyncE131
    https://github.com/greiman/SdFat @ ^2.3.0
    https://github.com/mathieucarbou/ESPAsyncWebServer
    ottowinter/AsyncMqttClient-esphome
    https://github.com/paulstoffregen/Time
    https://github.com/MartinMueller2003/Artnet
    https://github.com/MartinMueller2003/Espalexa
    https://github.com/MartinMueller2003/SimpleFTPServer
    https://github.com/bitbank2/unzipLIB
extra_scripts =       
    pre:.scripts/pio-version.py
    post:.scripts/CopyTargets.py
build_flags =
    -D ENABLE_DEDICATED_SPI=1 ; instruct SdFat to take ownership of the spi device
    -D SDFAT_FILE_TYPE=3 ; SdFat full support
    -D USE_LONG_FILE_NAMES=1 ; SdFat
    -D MAINTAIN_FREE_CLUSTER_COUNT=1 ; SdFat
    -D CHECK_FLASH_PROGRAMMING=0 ; SdFat
    -D INCLUDE_SDIOS=0 ; SdFat
    -D SUPPORT_FTP
    -D NOBYFOUR=1 ; reduced unzip table size
    -D DISABLE_FS_H_WARNING=1
    -mtext-section-literals
    -Wl,-Map=firmware.map
    -Wl,--cref
;    -fstack-protector-all
lib_ignore =
	ESP Async WebServer	; force the use of the esphome version
	AsyncTCP			; force the use of the esphome version
	LittleFS_esp32		; force the use of the ESP32 built into the core version

[esp32]
platform = espressif32 @ 6.10.0
platform_packages = tool-esptoolpy
board_build.filesystem = littlefs
board_build.partitions = ESP32_partitions.csv
monitor_filters = esp32_exception_decoder, colorize
; monitor_filters = esp32_exception_decoder, time
build_flags =
    ${env.build_flags}
    -D ARDUINO_LOOP_STACK_SIZE=12288
    -D DEFAULT_FTP_SERVER_NETWORK_TYPE_ESP32=6
    -D DEFAULT_STORAGE_TYPE_ESP32=2
    -D SUPPORT_UNZIP=1
    -D CONFIG_DISABLE_HAL_LOCKS=1
    -D CONFIG_RMT_ISR_IRAM_SAFE=yes
;    -D USE_SERIAL_DEBUG_COUNTERS=1
;    -D USE_RMT_DEBUG_COUNTERS=1
;    -D USE_PIXEL_DEBUG_COUNTERS=1
;    -D DEBUG_RMT_XLAT_ISSUES=1
;    -D DEBUG_FILE_HANDLES=1
build_unflags =
    ${env.build_unflags}
    -D BOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -mfix-esp32-psram-cache-strategy=memw
lib_deps =
    ${env.lib_deps}
    mathieucarbou/AsyncTCP @ ^3.2.14
    mathieucarbou/OneWire @ ^2.3.9
    https://github.com/matmunk/DS18B20
    olikraus/U8g2@^2.36.5
    Preferences
extra_scripts = 
    ${env.extra_scripts}
    .scripts/replace_fs.py
    post:post_efu.py


[esp32_cust]
extends = esp32
build_type = release
build_flags =
    ${esp32.build_flags}
    -D SUPPORT_OLED
    -D FLASH_EXTRA_IMAGES
    -D ESPS_VERSION="4.xXx"
 ;   -DCORE_DEBUG_LEVEL=5

[env:esp32_bigboi]
extends = esp32_cust
board = bigboi
build_flags =
    ${esp32_cust.build_flags}
    -D BOARD_NAME=\"esp32_BigBoi\"
    -D BOARD_ESP32_WROVER


; big boi (pixel Rick)
[env:esp32_bigboi_debug]
extends = esp32_cust
board = bigboi
build_type = debug
build_flags =
    ${esp32_cust.build_flags}
debug_tool = custom
monitor_speed = 115200
debug_init_cmds =
  target remote localhost:3333
  monitor reset halt
  flushregs

; small man (trickle pixel)
[env:esp32_smallman]
extends = esp32_cust
board = smallman
build_flags =
    ${esp32_cust.build_flags}
    -D BOARD_NAME=\"esp32_smallman\"
    -D BOARD_ESP32_DEV4

; tiny dancer
[env:esp32_tiny]
extends = esp32_cust
board = tiny
build_flags =
    ${esp32_cust.build_flags}
    -D BOARD_NAME=\"esp32_tinydancer\"
    -D BOARD_ESP32_TINY
build_unflags =
    -D SUPPORT_OLED

; small man (trickle pixel)
[env:esp32_babyboi]
extends = esp32_cust
board = tiny
build_flags =
    ${esp32_cust.build_flags}
    -D BOARD_NAME=\"esp32_babyboi\"
    -D BOARD_ESP32_D1JT

; small man (trickle pixel)
[env:esp32_babyboi_dbg]
extends = esp32_cust
board = tiny
build_type = debug

build_flags =
    ${esp32_cust.build_flags}
    -D BOARD_NAME=\"esp32_babyboi\"
    -D BOARD_ESP32_D1JT

[alias:post_efu]
targets = buildprog, buildfs
