name: ESPixelStick CI
on: [push, pull_request, workflow_dispatch]
env:
  VERSION_BASE: '4.xXx'
jobs:
  firmware:
    strategy:
      matrix:
        include:
        - target: esp32_bigboi
          chip: esp32
        - target: esp32_tiny
          chip: esp32
        - target: esp32_smallman
          chip: esp32
        - target: esp32_babyboi
          chip: esp32
        - target: esp32_teth
          chip: esp32
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create version file
      run: 'mkdir firmware

        echo "${VERSION_BASE}-ci${GITHUB_RUN_ID}" > firmware/VERSION

        '
    - name: Compile for ${{ matrix.target }}
      env:
        chip: ${{ matrix.chip }}
      run: 'pio run -e ${{ matrix.target }}

        '
    - name: Upload Firmware Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-binary-${{ matrix.target }}
        path: firmware
